version: '3'
services:

  mysql:
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data-dev:/data/mysql"
    env_file:
      - docker-compose.dev.mysql.env

  redis:
    ports:
      - "6379:6379"

  bot:
    ports:
      - "3000:80"
    volumes:
      - ".:/usr/src"
    env_file:
      - docker-compose.dev.bot.env
    command: npm run dev

volumes:
  mysql-data-dev: