version: '3'
services:

  mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine

  bot:
    build:
      context: .
    depends_on:
      - mysql
      - redis
